### PR TITLE
Added image Properties

### PR DESCRIPTION
**Pull request by HorribleGeek**
Use #floatleft to align it to left
Use #floatright to align it to right
Use #centre to align it to center

> Use these tags after the link. Eg: img.png#center
https://geekworld.coregossip.com/about/ - all 3 examples

### CODE REVIEW

**Comment by HorribleGeek** [comment]
I have added just the image properties, at the end and minified that part.

**Review by HorribleGeek — COMMENTED** [review]
Sorry for rewiting the whole stuff instead of pasting my part at the end.

I was working on a mobile device and for some reason was not able to copy just the last part. :P

**Comment by laozhu** [comment]
Hi @HorribleGeek, sorry for my later reply.

You should modify `./src/styles/partials/content.scss` before make a PR, I will build the src to production bundle.css.

BTW, I think class selector is simpler then attribute selector, maybe we can support both of them.

**Comment by HorribleGeek** [comment]
Unfortunately you are speaking to an idiot over here, I don't know much about all this. I'll close this PR!

**Pull request closed without merging**
